import { createStore, applyMiddleware } from 'redux';
import { createLogger } from 'redux-logger';
import reducer from '../reducers/reducer.js';

const logger = createLogger();

const initialState = {
    pullup: {
        MainDevice_GPIO_1_0: false,
        MainDevice_GPIO_1_1: false,
        MainDevice_GPIO_1_2: false,
        MainDevice_GPIO_1_3: false,
        MainDevice_GPIO_1_4: false,
        MainDevice_GPIO_1_5: false,
        MainDevice_GPIO_1_6: false,
        MainDevice_GPIO_1_7: false,
        MainDevice_GPIO_1_8: false,
        MainDevice_GPIO_1_9: false,
        MainDevice_GPIO_1_10: false,
        MainDevice_GPIO_1_11: false,
        MainDevice_GPIO_1_12: false,
        MainDevice_GPIO_1_13: false,
        MainDevice_GPIO_1_14: false,

        ExtentionDevice1_GPIO_1_0: false,
        ExtentionDevice1_GPIO_1_1: false,
        ExtentionDevice1_GPIO_1_2: false,
        ExtentionDevice1_GPIO_1_3: false,
        ExtentionDevice1_GPIO_1_4: false,
        ExtentionDevice1_GPIO_1_5: false,
        ExtentionDevice1_GPIO_1_6: false,
        ExtentionDevice1_GPIO_1_7: false,
        ExtentionDevice1_GPIO_1_8: false,
        ExtentionDevice1_GPIO_1_9: false,

        ExtentionDevice3_GPIO_1_0: false,
        ExtentionDevice3_GPIO_1_1: false,
        ExtentionDevice3_GPIO_1_2: false,
        ExtentionDevice3_GPIO_1_3: false,
        ExtentionDevice3_GPIO_1_4: false,
        ExtentionDevice3_GPIO_1_5: false,
        ExtentionDevice3_GPIO_1_6: false,
        ExtentionDevice3_GPIO_1_7: false,
        ExtentionDevice3_GPIO_1_8: false,
        ExtentionDevice3_GPIO_1_9: false,
        ExtentionDevice3_GPIO_1_10: false,
        ExtentionDevice3_GPIO_1_11: false,
        ExtentionDevice3_GPIO_1_12: false,
        ExtentionDevice3_GPIO_1_13: false,
        ExtentionDevice3_GPIO_1_14: false,

        ExtentionDevice3_GPIO_2_0: false,
        ExtentionDevice3_GPIO_2_1: false,
        ExtentionDevice3_GPIO_2_2: false,
        ExtentionDevice3_GPIO_2_3: false,
        ExtentionDevice3_GPIO_2_4: false,
    }, 
    voltage: {
        MainDevice_GPIO_1_0: false,
        MainDevice_GPIO_1_1: false,
        MainDevice_GPIO_1_2: false,
        MainDevice_GPIO_1_3: false,
        MainDevice_GPIO_1_4: false,
        MainDevice_GPIO_1_5: false,
        MainDevice_GPIO_1_6: false,
        MainDevice_GPIO_1_7: false,
        MainDevice_GPIO_1_8: false,
        MainDevice_GPIO_1_9: false,
        MainDevice_GPIO_1_10: false,
        MainDevice_GPIO_1_11: false,
        MainDevice_GPIO_1_12: false,
        MainDevice_GPIO_1_13: false,
        MainDevice_GPIO_1_14: false,

        ExtentionDevice1_GPIO_1_0: false,
        ExtentionDevice1_GPIO_1_1: false,
        ExtentionDevice1_GPIO_1_2: false,
        ExtentionDevice1_GPIO_1_3: false,
        ExtentionDevice1_GPIO_1_4: false,
        ExtentionDevice1_GPIO_1_5: false,
        ExtentionDevice1_GPIO_1_6: false,
        ExtentionDevice1_GPIO_1_7: false,
        ExtentionDevice1_GPIO_1_8: false,
        ExtentionDevice1_GPIO_1_9: false,

        ExtentionDevice3_GPIO_1_0: false,
        ExtentionDevice3_GPIO_1_1: false,
        ExtentionDevice3_GPIO_1_2: false,
        ExtentionDevice3_GPIO_1_3: false,
        ExtentionDevice3_GPIO_1_4: false,
        ExtentionDevice3_GPIO_1_5: false,
        ExtentionDevice3_GPIO_1_6: false,
        ExtentionDevice3_GPIO_1_7: false,
        ExtentionDevice3_GPIO_1_8: false,
        ExtentionDevice3_GPIO_1_9: false,
        ExtentionDevice3_GPIO_1_10: false,
        ExtentionDevice3_GPIO_1_11: false,
        ExtentionDevice3_GPIO_1_12: false,
        ExtentionDevice3_GPIO_1_13: false,
        ExtentionDevice3_GPIO_1_14: false,

        ExtentionDevice3_GPIO_2_0: false,
        ExtentionDevice3_GPIO_2_1: false,
        ExtentionDevice3_GPIO_2_2: false,
        ExtentionDevice3_GPIO_2_3: false,
        ExtentionDevice3_GPIO_2_4: false,
    }, 
    settingsVisible: {
        MainDevice_GPIO_1: false,
        ExtentionDevice1_GPIO_1: false,
        ExtentionDevice3_GPIO_1: false,
        ExtentionDevice3_GPIO_2: false,
    },
    graphVisible: {
        MainDevice_GPIO_1: false,
        ExtentionDevice1_GPIO_1: false,
        ExtentionDevice3_GPIO_1: false,
        ExtentionDevice3_GPIO_2: false,
    }
};

const store = createStore(
    reducer, 
    initialState, 
    applyMiddleware(logger));

export default store;